
load("//:test_utils.bzl", "assert_output")
load("defs.bzl", "rule_with_custom_span", "rule_without_custom_span")

oncall("build_infra")

rust_library(
    name = "library",
    srcs = glob(
        ["src/**/*.rs"],
    ),
)

rust_binary(
    name = "long_build_library",
    srcs = glob(
        ["long_running_binary/**/*.rs"],
    ),
    crate_root = "long_running_binary/main.rs",
)

rust_binary(
    name = "main",
    srcs = glob(
        ["bin/**/*.rs"],
    ),
    crate_root = "bin/main.rs",
    deps = [":library"],
)

rust_test(
    name = "test",
    srcs = glob(
        ["test/**/*.rs"],
    ),
    deps = [":library"],
)

assert_output(
    name = "check_main",
    command = "$(exe_target :main)",
    output = "hello world from rust toolchain",
)

rule_with_custom_span(
    name = "target_with_custom_span",
    target = ":long_build_library",
)

rule_without_custom_span(
    name = "target_without_custom_span",
    target = ":long_build_library",
)
